excerpt_separator: ""
animated: true
url: http://mhorga.org
title: Swift development blog
author: Marius Horga
description: A blog about games, graphics and mobile development. 
paginate: 5
google_analytics: "UA-64309195-1"
