excerpt_separator: ""
animated: true
pygments: true
markdown: kramdown
url: http://mhorga.org
title: Swift development blog
author: Marius Horga
description: A blog about iOS, watchOS, tvOS and OS X development. 
paginate: 5
google_analytics: "UA-64309195-1"
